### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by schriftgestalt** [hejpaul/glyphs-backdrop#1]
I got his from a user:
```
Details:
Traceback (most recent call last):

 File "vanillaBase.py", line 506, in action_

 File "plugin.py", line 259, in addGlyphButtonPressed

AttributeError: 'NoneType' object has no attribute 'parent'
```

**Comment by donaldzhu** [comment]
I have also experienced this issue, and it might also have been the reason why I wasn't able to restart Glyphs afterwards.

**Comment by schriftgestalt** [comment]
another one. Not sure from what version:
```
Details:
Traceback (most recent call last):

 File "vanillaBase.py", line 506, in action_
   self.callback(sender)

 File "plugin.py", line 269, in addGlyphButtonPressed
   self.drawFriends(Glyphs.font.selectedLayers[0])

 File "plugin.py", line 91, in drawFriends
   if g.completeBezierPath is not None:

AttributeError: 'NoneType' object has no attribute 'completeBezierPath'

App:3.0.2-3058 Plugin:(null)-(null)
``

**Comment by schriftgestalt** [comment]
one more:
```
Details:
Traceback (most recent call last):

 File "GlyphsApp/GlyphsApp/__init__.py", line 1273, in callback_

 File "plugin.py", line 27, in docActivated_
   self.updateWindowUI()

 File "plugin.py", line 250, in updateWindowUI
   self.currentWindow.glyphList.extend([{"Visibility": friend[1], "Status": " ", "Name": friend[0], "Position": friend[2], "layer": Glyphs.font.glyphs[friend[0]].layers[Glyphs.font.selectedLayers[0].layerId]} for friend in gl])

 File "plugin.py", line 250, in <listcomp>
   self.currentWindow.glyphList.extend([{"Visibility": friend[1], "Status": " ", "Name": friend[0], "Position": friend[2], "layer": Glyphs.font.glyphs[friend[0]].layers[Glyphs.font.selectedLayers[0].layerId]} for friend in gl])

AttributeError: 'NoneType' object has no attribute 'layers'

App:3.0.2-3058 Plugin:1.0-2
```
