### ISSUE TITLE
Crash reports

### ISSUE THREAD

**Issue by drawcard** [hejpaul/glyphs-backdrop#3]
From https://forum.glyphsapp.com/t/glyphs-crash-with-backdrop-plugin/18211

```
The Plugin Backdrop.glyphsReporter has caused a crash. Please update it by opening the Plugin Manager or re-downloading it from the original source.

Details:
Traceback (most recent call last):

  File "GlyphsApp/GlyphsApp/__init__.py", line 1273, in callback_

  File "plugin.py", line 27, in docActivated_
    self.updateWindowUI()

  File "plugin.py", line 223, in updateWindowUI
    n = self.currentGlyph.parent.name

AttributeError: 'NoneType' object has no attribute 'parent'

App:3.0.2-3058 Plugin:1.0-2
```

```
A plugin caused a crash

The Plugin Backdrop.glyphsReporter has caused a crash. Please update it by opening the Plugin Manager or re-downloading it from the original source.

Details:
Traceback (most recent call last):

  File "GlyphsApp/GlyphsApp/__init__.py", line 1273, in callback_

  File "plugin.py", line 27, in docActivated_
    self.updateWindowUI()

  File "plugin.py", line 250, in updateWindowUI
    self.currentWindow.glyphList.extend([{"Visibility": friend[1], "Status": " ", "Name": friend[0], "Position": friend[2], "layer": Glyphs.font.glyphs[friend[0]].layers[Glyphs.font.selectedLayers[0].layerId]} for friend in gl])

  File "plugin.py", line 250, in <listcomp>
    self.currentWindow.glyphList.extend([{"Visibility": friend[1], "Status": " ", "Name": friend[0], "Position": friend[2], "layer": Glyphs.font.glyphs[friend[0]].layers[Glyphs.font.selectedLayers[0].layerId]} for friend in gl])

AttributeError: 'NoneType' object has no attribute 'layers'

App:3.0.2-3058 Plugin:1.0-2
```

**Comment by schriftgestalt** [comment]
This is still a problem. Can you have a look?

**Comment by schriftgestalt** [comment]
here is another one: 
```
Traceback (most recent call last):

 File "vanillaList.py", line 52, in observeValueForKeyPath_ofObject_change_context_
   self._targetMethod()

 File "vanillaList.py", line 814, in _edit
   self._editCallback(self)

 File "plugin.py", line 153, in listEdited
   self.drawFriends(Glyphs.font.selectedLayers[0])

 File "plugin.py", line 91, in drawFriends
   if g.completeBezierPath is not None:

AttributeError: 'NoneType' object has no attribute 'completeBezierPath'
```

**Comment by schriftgestalt** [comment]
ping

**Comment by schriftgestalt** [comment]
ping

**Comment by schriftgestalt** [comment]
Here is another report: 
```
Details:
Traceback (most recent call last):

  File "GlyphsApp/GlyphsApp/plugins.py", line 1413, in raiseException_

  File "GlyphsApp/GlyphsApp/plugins.py", line 1229, in drawBackgroundForLayer_options_

  File "plugin.py", line 115, in background
    if not self.toolStatus: self.openWindow()
                            ^^^^^^^^^^^^^^^^^

  File "plugin.py", line 68, in openWindow
    self.updateWindowUI()

  File "plugin.py", line 228, in updateWindowUI
    if not self.currentGlyph or not self.currentWindow:
           ^^^^^^^^^^^^^^^^^

AttributeError: 'Backdrop' object has no attribute 'currentGlyph'

App:3.3-3317 Plugin:1.1.1-5 System:14.6.1 
```

**Comment by schriftgestalt** [comment]
and another one:
```
Details:
Traceback (most recent call last):

 File "vanillaList.py", line 54, in observeValueForKeyPath_ofObject_change_context_
   self._targetMethod()

 File "vanillaList.py", line 767, in _edit
   self._editCallback(self)

 File "plugin.py", line 156, in listEdited
   friends = self.currentWindow.glyphList.get()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'glyphList'
```
